# app/config/security.yml
security:
   encoders:
       FOS\UserBundle\Model\UserInterface: sha512

   role_hierarchy:
       ROLE_ADMIN:       ROLE_USER

   providers:
       fos_userbundle:
           id: fos_user.user_provider.username

   firewalls:
       main:
           pattern: ^/
           form_login:
               default_target_path: /administration
               login_path: /login
               check_path: /login_check
               provider: fos_userbundle
           logout:
               path:    /logout
               target: /rechercheIndex
              # provider: fos_userbundle
              # csrf_provider: form.csrf_provider

           anonymous:    true

   access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/administration, role: ROLE_USER }