<?php

namespace MoteurRechercheBundle\Repository;

/**
 * AnalyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyseRepository extends \Doctrine\ORM\EntityRepository
{

	public function rechercheAnalyse($nomAnalyse){
		$queryBuider = $this->createQueryBuilder('a');
		$queryBuider ->where('a.nomAnalyse LIKE :nomAnalyse OR a.natureAnalyse LIKE :nomAnalyse')
			->orderBy('a.nomAnalyse', 'ASC')
			->setParameter('nomAnalyse','%'.$nomAnalyse.'%');

		return $queryBuider->getQuery()->getResult();	
	}

public function rechercheAnalyseAvecLabo($nomAnalyse,$nomLaboratoire){
		$queryBuider = $this->createQueryBuilder('a');
		$queryBuider ->where('a.nomAnalyse LIKE :nomAnalyse OR a.natureAnalyse LIKE :nomAnalyse')
			->setParameter('nomAnalyse','%'.$nomAnalyse.'%')
			->andWhere('a.laboratoire = :laboratoire')
			->setParameter('laboratoire', $nomLaboratoire)
			->orderBy('a.nomAnalyse', 'ASC');
			//->setParameter('nomLaboratoire', $nomLaboratoire);


	/*		 $qb->where('a.author = :author')
       ->setParameter('author', $author)
     ->andWhere('a.date < :year')
       ->setParameter('year', $year)
     ->orderBy('a.date', 'DESC')*/

		return $queryBuider->getQuery()->getResult();	
	}

// Ne fonctionne pas
	public function rechercheAnalyseAvecMicroOrg($nomAnalyse,$nomMicroOrganisme){
		$queryBuider = $this->createQueryBuilder('a');
		$queryBuider ->where('a.nomAnalyse LIKE :nomAnalyse OR a.natureAnalyse LIKE :nomAnalyse')
			->setParameter('nomAnalyse','%'.$nomAnalyse.'%')
			->andWhere('a.microOrganisme_analyse = :microOrganisme_analyse')
			->setParameter('microOrganisme_analyse', $nomMicroOrganisme);
			//->orderBy('a.nomAnalyse', 'ASC');

		return $queryBuider->getQuery()->getResult();	
	}

	
	public function rechercheAnalyseLabo($nomLaboratoire){
		$queryBuider = $this->createQueryBuilder('a');
		$queryBuider ->where('a.laboratoire = :laboratoire')
			->setParameter('laboratoire', $nomLaboratoire)
			->orderBy('a.nomAnalyse', 'ASC');

		return $queryBuider->getQuery()->getResult();	
	}

	

		public function rechercheAnalyseButton($lettre){
		$queryBuider = $this->createQueryBuilder('a');
		$queryBuider ->where('a.nomAnalyse LIKE :nomAnalyse')
			->orderBy('a.nomAnalyse', 'ASC')
			->setParameter('nomAnalyse',$lettre.'%');

		return $queryBuider->getQuery()->getResult();	
	}




}
