<?php

namespace MoteurRechercheBundle\Repository;

/**
 * MicroOrganismeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MicroOrganismeRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getListeMicroOrganisme()
	{
		$queryBuider = $this->createQueryBuilder('m');
		$queryBuider ->where("m.nomMicroOrganisme != '' ")
			->orderBy('m.nomMicroOrganisme', 'ASC');
		return $queryBuider->getQuery()->getResult();	
	}
}
