<?php

namespace MoteurRechercheBundle\Repository;

/**
 * NomenclatureBBhnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureBBhnRepository extends \Doctrine\ORM\EntityRepository
{
}
