moteur_recherche_analyse:
    resource: "@MoteurRechercheBundle/Resources/config/routing/analyse.yml"
    prefix:   /analyse

moteur_recherche_conditionprelevement:
        resource: "@MoteurRechercheBundle/Resources/config/routing/conditionprelevement.yml"
        prefix:   /conditionprelevement

moteur_recherche_conservationavanttransport:
        resource: "@MoteurRechercheBundle/Resources/config/routing/conservationavanttransport.yml"
        prefix:   /conservationavanttransport

moteur_recherche_delairesultat:
        resource: "@MoteurRechercheBundle/Resources/config/routing/delairesultat.yml"
        prefix:   /delairesultat

moteur_recherche_ficheprescription:
        resource: "@MoteurRechercheBundle/Resources/config/routing/ficheprescription.yml"
        prefix:   /ficheprescription

moteur_recherche_laboratoire:
        resource: "@MoteurRechercheBundle/Resources/config/routing/laboratoire.yml"
        prefix:   /laboratoire

moteur_recherche_microorganisme:
        resource: "@MoteurRechercheBundle/Resources/config/routing/microorganisme.yml"
        prefix:   /microorganisme

moteur_recherche_naturematrice:
        resource: "@MoteurRechercheBundle/Resources/config/routing/naturematrice.yml"
        prefix:   /naturematrice

moteur_recherche_natureprelevement:
        resource: "@MoteurRechercheBundle/Resources/config/routing/natureprelevement.yml"
        prefix:   /natureprelevement

moteur_recherche_principemethode:
        resource: "@MoteurRechercheBundle/Resources/config/routing/principemethode.yml"
        prefix:   /principemethode

moteur_recherche_renseignementclinique:
        resource: "@MoteurRechercheBundle/Resources/config/routing/renseignementclinique.yml"
        prefix:   /renseignementclinique

moteur_recherche_secteur:
        resource: "@MoteurRechercheBundle/Resources/config/routing/secteur.yml"
        prefix:   /secteur

moteur_recherche_transport:
        resource: "@MoteurRechercheBundle/Resources/config/routing/transport.yml"
        prefix:   /transport

moteur_recherche_insertion:
    path:     /insertion
    defaults: { _controller: MoteurRechercheBundle:Default:jeuxInsertion }

moteur_recherche_homepage:
        resource: "@MoteurRechercheBundle/Resources/config/routing/recherche.yml"
        prefix:   /rechercheIndex

moteur_recherche_administration:
    path:     /administration
    defaults: { _controller: MoteurRechercheBundle:Default:administration }

moteur_recherche_administration_analyse:
    path:     /administration/analyse
    defaults: { _controller: MoteurRechercheBundle:Analyse:index }

moteur_recherche_administration_FichePrescription:
    path:     /administration/ficheprescription
    defaults: { _controller: MoteurRechercheBundle:FichePrescription:index }

moteur_recherche_administration_PrincipeMethode:
    path:     /administration/fichemethode
    defaults: { _controller: MoteurRechercheBundle:PrincipeMethode:index }

moteur_recherche_administration_NaturePrelevement:
    path:     /administration/natureprelevement
    defaults: { _controller: MoteurRechercheBundle:NaturePrelevement:index }

moteur_recherche_administration_RenseignementClinique:
    path:     /administration/renseignementclinique
    defaults: { _controller: MoteurRechercheBundle:RenseignementClinique:index }

moteur_recherche_administration_ConditionPrelevement:
    path:     /administration/conditionprelevement
    defaults: { _controller: MoteurRechercheBundle:ConditionPrelevement:index }

moteur_recherche_administration_Transport:
    path:     /administration/transport
    defaults: { _controller: MoteurRechercheBundle:Transport:index }

moteur_recherche_administration_NatureMatrice:
    path:     /administration/naturematrice
    defaults: { _controller: MoteurRechercheBundle:NatureMatrice:index }

moteur_recherche_administration_ConservationAvantTransport:
    path:     /administration/conservationavanttransport
    defaults: { _controller: MoteurRechercheBundle:ConsersationAvantTransport:index }

moteur_recherche_administration_DelaiResultat:
    path:     /administration/delairesultat
    defaults: { _controller: MoteurRechercheBundle:DelaiResultat:index }

moteur_recherche_administration_MicroOrganisme:
    path:     /administration/microorganisme
    defaults: { _controller: MoteurRechercheBundle:MicroOrganisme:index }

moteur_recherche_administration_Laboratoire:
    path:     /administration/laboratoire
    defaults: { _controller: MoteurRechercheBundle:Laboratoire:index }

moteur_recherche_administration_Secteur:
    path:     /administration/secteur
    defaults: { _controller: MoteurRechercheBundle:Secteur:index }