moteur_recherche_analyse:
    resource: "@MoteurRechercheBundle/Resources/config/routing/analyse.yml"
    prefix:   /administration/analyse

moteur_recherche_administration_ConditionPrelevement:
    path:     /administration/conditionprelevement
    defaults: { _controller: MoteurRechercheBundle:ConditionPrelevement:index }

moteur_recherche_conditionprelevement:
    resource: "@MoteurRechercheBundle/Resources/config/routing/conditionprelevement.yml"
    prefix:     /administration/conditionprelevement

moteur_recherche_conservationavanttransport:
    resource: "@MoteurRechercheBundle/Resources/config/routing/conservationavanttransport.yml"
    prefix:   /administration/conservationavanttransport

moteur_recherche_administration_ConservationAvantTransport:
    path:     /administration/conservationavanttransport
    defaults: { _controller: MoteurRechercheBundle:ConservationAvantTransport:index }

moteur_recherche_delairesultat:
        resource: "@MoteurRechercheBundle/Resources/config/routing/delairesultat.yml"
        prefix:   /administration/delairesultat

moteur_recherche_ficheprescription:
        resource: "@MoteurRechercheBundle/Resources/config/routing/ficheprescription.yml"
        prefix:   /administration/ficheprescription

moteur_recherche_tube:
        resource: "@MoteurRechercheBundle/Resources/config/routing/tube.yml"
        prefix:   /administration/tube

moteur_recherche_nomenclaturebbhn:
        resource: "@MoteurRechercheBundle/Resources/config/routing/nomenclaturebbhn.yml"
        prefix:   /administration/nomenclaturebbhn

moteur_recherche_laboratoire:
        resource: "@MoteurRechercheBundle/Resources/config/routing/laboratoire.yml"
        prefix:   /administration/laboratoire

moteur_recherche_microorganisme:
        resource: "@MoteurRechercheBundle/Resources/config/routing/microorganisme.yml"
        prefix:   /administration/microorganisme

moteur_recherche_naturematrice:
        resource: "@MoteurRechercheBundle/Resources/config/routing/naturematrice.yml"
        prefix:   /administration/naturematrice

moteur_recherche_natureprelevement:
        resource: "@MoteurRechercheBundle/Resources/config/routing/natureprelevement.yml"
        prefix:   /administration/natureprelevement

moteur_recherche_principemethode:
        resource: "@MoteurRechercheBundle/Resources/config/routing/principemethode.yml"
        prefix:   /administration/principemethode

moteur_recherche_renseignementclinique:
        resource: "@MoteurRechercheBundle/Resources/config/routing/renseignementclinique.yml"
        prefix:   /administration/renseignementclinique

moteur_recherche_secteur:
        resource: "@MoteurRechercheBundle/Resources/config/routing/secteur.yml"
        prefix:   /administration/secteur

moteur_recherche_transport:
        resource: "@MoteurRechercheBundle/Resources/config/routing/transport.yml"
        prefix:   /administration/transport

moteur_recherche_insertion:
    path:     /administration/insertion
    defaults: { _controller: MoteurRechercheBundle:Default:jeuxInsertion }

moteur_recherche_vidage:
    path:     /administration/vidageBDD
    defaults: { _controller: MoteurRechercheBundle:Default:vidageTable }

moteur_recherche_PDF:
    path:     /administration/PDF
    defaults: { _controller: MoteurRechercheBundle:Default:generatePDF }

moteur_recherche_homepage:
        resource: "@MoteurRechercheBundle/Resources/config/routing/recherche.yml"
        prefix:   /rechercheIndex

moteur_recherche_administration:
    path:     /administration
    defaults: { _controller: MoteurRechercheBundle:Default:administration }

moteur_recherche_administration_analyse:
    path:     /administration/analyse
    defaults: { _controller: MoteurRechercheBundle:Analyse:index }

moteur_recherche_administration_FichePrescription:
    path:     /administration/ficheprescription
    defaults: { _controller: MoteurRechercheBundle:FichePrescription:index }

moteur_recherche_administration_PrincipeMethode:
    path:     /administration/fichemethode
    defaults: { _controller: MoteurRechercheBundle:PrincipeMethode:index }

moteur_recherche_administration_NaturePrelevement:
    path:     /administration/natureprelevement
    defaults: { _controller: MoteurRechercheBundle:NaturePrelevement:index }

moteur_recherche_administration_RenseignementClinique:
    path:     /administration/renseignementclinique
    defaults: { _controller: MoteurRechercheBundle:RenseignementClinique:index }

moteur_recherche_administration_Transport:
    path:     /administration/transport
    defaults: { _controller: MoteurRechercheBundle:Transport:index }

moteur_recherche_administration_NatureMatrice:
    path:     /administration/naturematrice
    defaults: { _controller: MoteurRechercheBundle:NatureMatrice:index }

moteur_recherche_administration_DelaiResultat:
    path:     /administration/delairesultat
    defaults: { _controller: MoteurRechercheBundle:DelaiResultat:index }

moteur_recherche_administration_MicroOrganisme:
    path:     /administration/microorganisme
    defaults: { _controller: MoteurRechercheBundle:MicroOrganisme:index }

moteur_recherche_administration_Laboratoire:
    path:     /administration/laboratoire
    defaults: { _controller: MoteurRechercheBundle:Laboratoire:index }

moteur_recherche_administration_Secteur:
    path:     /administration/secteur
    defaults: { _controller: MoteurRechercheBundle:Secteur:index }

moteur_recherche_administration_Tube:
    path:     /administration/tube
    defaults: { _controller: MoteurRechercheBundle:Tube:index }

moteur_recherche_administration_NomenclatureBBHN:
    path:     /administration/nomenclatureBBHN
    defaults: { _controller: MoteurRechercheBundle:NomenclatureBBhn:index }