MoteurRechercheBundle\Entity\NomenclatureBBhn:
    type: entity
    table: null
    repositoryClass: MoteurRechercheBundle\Repository\NomenclatureBBhnRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        valeurNomenclature:
            type: string
            length: 255
            nullable: true
    oneToMany:
        analyses:
            targetEntity: Analyse
            mappedBy: nomenclatureBBhn
    lifecycleCallbacks: {  }
