MoteurRechercheBundle\Entity\Tube:
    type: entity
    table: null
    repositoryClass: MoteurRechercheBundle\Repository\TubeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomImageTube:
            type: string
            length: 255
            nullable: true
    oneToMany: 
        analyses: 
            targetEntity: Analyse 
            mappedBy: tube
    lifecycleCallbacks: {  }
