rechercheIndex:
    path:     /
    defaults: { _controller: "MoteurRechercheBundle:RechercheIndex:index" }
    methods:  GET
RechercheAction:
    path:     /
    defaults: { _controller: "MoteurRechercheBundle:RechercheIndex:recherche" }
    methods:  POST
ouvrir_analyse_simple:
    path:     /affichageSimple/{id}
    defaults: { _controller: "MoteurRechercheBundle:RechercheIndex:ouvrirAnalyseSimple" }
recherche:
    path: /recherche
    defaults: { _controller: MoteurRechercheBundle:RechercheIndex:rechercheAjax }
    methods: POST