rechercheIndex:
    path:     /
    defaults: { _controller: "MoteurRechercheBundle:RechercheIndex:index" }
    methods:  GET
RechercheAction:
    path:     /{saisie}
    defaults: { _controller: "MoteurRechercheBundle:RechercheIndex:recherche" }
    methods:  GET